PROMPT Creating tables 

-- สร้างตาราง customers
create table customers (
  customer_id     integer generated by default on null as identity,
  email_address   varchar2(255 char) not null,
  full_name       varchar2(255 char),
  first_name      varchar2(255 char),
  last_name       varchar2(255 char))
;

-- สร้างตาราง stores
create table stores (
  store_id          integer generated by default on null as identity,
  store_name        varchar2(255 char) not null,
  web_address       varchar2(100 char),
  physical_address  varchar2(512 char),
  latitude          number,
  longitude         number,
  logo              blob,
  logo_mime_type    varchar2(512 char),
  logo_filename     varchar2(512 char),
  logo_charset      varchar2(512 char),
  logo_last_updated date)
;

-- สร้างตาราง products
create table products (
  product_id         integer generated by default on null as identity,
  product_name       varchar2(255 char) not null,
  unit_price         number(10,2),
  product_details    blob,
  product_image      blob,
  image_mime_type    varchar2(512 char),
  image_filename     varchar2(512 char),
  image_charset      varchar2(512 char),
  image_last_updated date)
;

-- สร้างตาราง orders
create table orders (
  order_id        integer 
                  generated by default on null as identity,
  order_datetime  timestamp not null,
  customer_id     integer not null,
  order_status    varchar2(10 char) not null,
  store_id        integer not null)
;

-- สร้างตาราง shipments
create table shipments (
  shipment_id          integer 
                       generated by default on null as identity,
  store_id             integer not null,
  customer_id          integer not null,
  delivery_address     varchar2(512 char) not null,
  shipment_status      varchar2(100 char) not null)
;

-- สร้างตาราง order_items
create table order_items (
  order_id        integer not null,
  line_item_id    integer not null,
  product_id      integer not null,
  unit_price      number(10,2) not null,
  quantity        integer not null,
  shipment_id     integer)
;

-- สร้างตาราง inventory
create table inventory (
  inventory_id          integer
                        generated by default on null as identity,
  store_id              integer not null,
  product_id            integer not null,
  product_inventory     integer not null)
;


/*
PROMPT กำลังสร้างดัชนี

-- สร้างดัชนี customers_name_i บนตาราง customers สำหรับคอลัมน์ full_name
create index customers_name_i on customers (full_name);

-- สร้างดัชนี orders_customer_id_i บนตาราง orders สำหรับคอลัมน์ customer_id
create index orders_customer_id_i on orders (customer_id);

-- สร้างดัชนี orders_store_id_i บนตาราง orders สำหรับคอลัมน์ store_id
create index orders_store_id_i on orders (store_id);

-- สร้างดัชนี shipments_store_id_i บนตาราง shipments สำหรับคอลัมน์ store_id
create index shipments_store_id_i on shipments (store_id);

-- สร้างดัชนี shipments_customer_id_i บนตาราง shipments สำหรับคอลัมน์ customer_id
create index shipments_customer_id_i on shipments (customer_id);

-- สร้างดัชนี order_items_shipment_id_i บนตาราง order_items สำหรับคอลัมน์ shipment_id
create index order_items_shipment_id_i on order_items (shipment_id);

-- สร้างดัชนี inventory_product_id_i บนตาราง inventory สำหรับคอลัมน์ product_id
create index inventory_product_id_i on inventory (product_id);
*/
